
pub fn keycode_to_vk_keycode(k: sdl2::keyboard::Keycode) -> Option<i32> {
  use sdl2::keyboard::Keycode;
  use winapi::um::winuser;
  match k {
    Keycode::A => Some(0x41),
    Keycode::B => Some(0x42),
    Keycode::C => Some(0x43),
    Keycode::D => Some(0x44),
    Keycode::E => Some(0x45),
    Keycode::F => Some(0x46),
    Keycode::G => Some(0x47),
    Keycode::H => Some(0x48),
    Keycode::I => Some(0x49),
    Keycode::J => Some(0x4A),
    Keycode::K => Some(0x4B),
    Keycode::L => Some(0x4C),
    Keycode::M => Some(0x4D),
    Keycode::N => Some(0x4E),
    Keycode::O => Some(0x4F),
    Keycode::P => Some(0x50),
    Keycode::Q => Some(0x51),
    Keycode::R => Some(0x52),
    Keycode::S => Some(0x53),
    Keycode::T => Some(0x54),
    Keycode::U => Some(0x55),
    Keycode::V => Some(0x56),
    Keycode::W => Some(0x57),
    Keycode::X => Some(0x58),
    Keycode::Y => Some(0x59),
    Keycode::Z => Some(0x5A),
    Keycode::Num1 => Some(0x31),
    Keycode::Num2 => Some(0x32),
    Keycode::Num3 => Some(0x33),
    Keycode::Num4 => Some(0x34),
    Keycode::Num5 => Some(0x35),
    Keycode::Num6 => Some(0x36),
    Keycode::Num7 => Some(0x37),
    Keycode::Num8 => Some(0x38),
    Keycode::Num9 => Some(0x39),
    Keycode::Num0 => Some(0x30),
    Keycode::Return => Some(winuser::VK_RETURN),
    Keycode::Escape => Some(winuser::VK_ESCAPE),
    Keycode::Backspace => Some(winuser::VK_BACK),
    Keycode::Tab => Some(winuser::VK_TAB),
    Keycode::Space => Some(winuser::VK_SPACE),
    Keycode::Minus  => Some(winuser::VK_OEM_MINUS),
    Keycode::Comma => Some(winuser::VK_OEM_COMMA),
    Keycode::Period => Some(winuser::VK_OEM_PERIOD),
    Keycode::F1 => Some(winuser::VK_F1),
    Keycode::F2 => Some(winuser::VK_F2),
    Keycode::F3 => Some(winuser::VK_F3),
    Keycode::F4 => Some(winuser::VK_F4),
    Keycode::F5 => Some(winuser::VK_F5),
    Keycode::F6 => Some(winuser::VK_F6),
    Keycode::F7 => Some(winuser::VK_F7),
    Keycode::F8 => Some(winuser::VK_F8),
    Keycode::F9 => Some(winuser::VK_F9),
    Keycode::F10 => Some(winuser::VK_F10),
    Keycode::F11 => Some(winuser::VK_F11),
    Keycode::F12 => Some(winuser::VK_F12),
    Keycode::PrintScreen => Some(winuser::VK_PRINT),
    Keycode::ScrollLock => Some(winuser::VK_SCROLL),
    Keycode::Pause => Some(winuser::VK_PAUSE),
    Keycode::Insert => Some(winuser::VK_INSERT),
    Keycode::Home => Some(winuser::VK_HOME),
    Keycode::PageUp => Some(winuser::VK_PRIOR),
    Keycode::Delete => Some(winuser::VK_DELETE),
    Keycode::End => Some(winuser::VK_END),
    Keycode::PageDown => Some(winuser::VK_NEXT),
    Keycode::Right => Some(winuser::VK_RIGHT),
    Keycode::Left => Some(winuser::VK_LEFT),
    Keycode::Down => Some(winuser::VK_DOWN),
    Keycode::Up => Some(winuser::VK_UP),
    Keycode::NumLockClear => Some(winuser::VK_NUMLOCK),
    Keycode::Kp1 => Some(winuser::VK_NUMPAD1),
    Keycode::Kp2 => Some(winuser::VK_NUMPAD2),
    Keycode::Kp3 => Some(winuser::VK_NUMPAD3),
    Keycode::Kp4 => Some(winuser::VK_NUMPAD4),
    Keycode::Kp5 => Some(winuser::VK_NUMPAD5),
    Keycode::Kp6 => Some(winuser::VK_NUMPAD6),
    Keycode::Kp7 => Some(winuser::VK_NUMPAD7),
    Keycode::Kp8 => Some(winuser::VK_NUMPAD8),
    Keycode::Kp9 => Some(winuser::VK_NUMPAD9),
    Keycode::Kp0 => Some(winuser::VK_NUMPAD0),
    Keycode::F13 => Some(winuser::VK_F13),
    Keycode::F14 => Some(winuser::VK_F14),
    Keycode::F15 => Some(winuser::VK_F15),
    Keycode::F16 => Some(winuser::VK_F16),
    Keycode::F17 => Some(winuser::VK_F17),
    Keycode::F18 => Some(winuser::VK_F18),
    Keycode::F19 => Some(winuser::VK_F19),
    Keycode::F20 => Some(winuser::VK_F20),
    Keycode::F21 => Some(winuser::VK_F21),
    Keycode::F22 => Some(winuser::VK_F22),
    Keycode::F23 => Some(winuser::VK_F23),
    Keycode::F24 => Some(winuser::VK_F24),
    Keycode::Execute => Some(winuser::VK_EXECUTE),
    Keycode::Help => Some(winuser::VK_HELP),
    Keycode::Menu => Some(winuser::VK_LMENU),
    Keycode::Select => Some(winuser::VK_SELECT),
    Keycode::Undo => Some(winuser::VK_SELECT),
    Keycode::LCtrl => Some(winuser::VK_LCONTROL),
    Keycode::LShift => Some(winuser::VK_LSHIFT),
    Keycode::LAlt => Some(winuser::VK_MENU),
    Keycode::LGui => Some(winuser::VK_LMENU),
    Keycode::RCtrl => Some(winuser::VK_RCONTROL),
    Keycode::RShift => Some(winuser::VK_RSHIFT),
    Keycode::RAlt => Some(winuser::VK_RMENU),
    Keycode::RGui => Some(winuser::VK_RMENU),
    Keycode::CapsLock => Some(winuser::VK_CAPITAL),
    _ => None
  }
}

pub fn map_mouse_btn(mouse_btn: sdl2::mouse::MouseButton) -> i32 {
  use sdl2::mouse::MouseButton;
  match mouse_btn {
      MouseButton::Left => 1,
      MouseButton::Right => 2,
      MouseButton::Middle => 4,
      _ => 4, // Seems the safest?
  }
}
